In [ ]:
#Демонстрация импортирования библиотеки Numpy и демонстрация атрибутов
import numpy as np
a = np.array([1, 2, 3, 4])
print('Форма массива: ', a.shape)
print('Тип данных массива: ', a.dtype)


Форма массива:  (4,)
Тип данных массива:  int64


In [ ]:
#Примеры создания массивов
#1. Создание массива из списка
list_data = [1, 2, 3, 4, 5, 6, 7]
array_list = np.array(list_data)
print('Массив из списка: \n', array_list)
#2. Создание массивов с помощью функций
zero_array = np.zeros((5, 6))#создаем массив(матрицу), состоящую из 5 строк и 6 столбцов заполненную нулями
print('массив нулей: \n', zero_array)
one_array = np.ones((2, 5))#массив едениц из 2 строк и 5 столбцов
print('массив едениц: \n', one_array)
range_array = np.arange(0, 12, 4)#создает массив от 0 до 12 не включая 12 с шагом 4
print('массив с arange: \n', range_array)

Массив из списка
 [1 2 3 4 5 6 7]
массив нулей
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
массив едениц
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
массив с arange
 [0 4 8]


In [ ]:
#создадим для теста трехмерный массив
list_3d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_3d = np.array(list_3d)
#далее выполним получение отдельного элемента
element = array_3d[1, 0]
print('Элемент [1, 0] в array_3d: ', element)
#срез
sub_array = array_3d[0:2, 1:3]
print('Срез: \n', sub_array)
#извлечение одного столбца
column = array_3d[:, 2]
print( 'Третий столбец: ', column)

Элемент [1, 0] в array_3d:  4
Срез: 
 [[2 3]
 [5 6]]
Третий столбец [3 6 9]


In [ ]:
# Создадим два массива для операций
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Поэлементное сложение
sum_array = a + b
print("Поэлементное сложение a + b:", sum_array)

# Поэлементное умножение
mult_array = a * b
print("Поэлементное умножение a * b:", mult_array)

# Вычисление средней величины
mean_value = np.mean(a)
print("Среднее значение элементов массива a:", mean_value)

# Вычисление суммы всех элементов
sum_value = np.sum(b)
print("Сумма элементов массива b:", sum_value)

# Вычисление максимального значения в массиве
max_value = np.max(mult_array)
print("Максимальное значение в mult_array:", max_value)
min_value = np.min(mult_array)
print("Минимальное значение в mult_array:", min_value)
#нормализация значений
#создадим отдельный массив чисел
d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
max_d = np.max(d)#максимальное в d
min_d = np.min(d)#минимальное в d
norm = (mult_array - min_d)/(max_d - min_d)
print("Нормализация значений в d:", norm)


Поэлементное сложение a + b: [5 7 9]
Поэлементное умножение a * b: [ 4 10 18]
Среднее значение элементов массива a: 2.0
Сумма элементов массива b: 15
Максимальное значение в mult_array: 18
Минимальное значение в mult_array: 4
Нормализация значений в d: [0.42857143 1.28571429 2.42857143]
